version: '3'
services:
  app:
    build:
      context: app
      dockerfile: ./Dockerfile
    image: hello_world
    env_file:
      - .env
    stop_signal: SIGKILL
    ports:
      - 8080:8080

  # the Prometheus server
  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./build/prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  # Grafana for visualization
  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - ./build/grafana/config.ini:/etc/grafana/grafana.ini
      - ./build/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./build/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./build/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
